### ISSUE TITLE
writing, closing, and then reopening a Sophia db in one Python session results in segfault on exit

### ISSUE THREAD

**Issue by lebedov** [coleifer/sophy#10]
If I create and close a Sophia db and then try to open and read from it in the same Python session, Python segfaults on exit (i.e., after printing the db contents in the example below). Creating the db in one session and then opening and reading from it in another succeeds without any segfault. I'm using bddf3da with Python 2.7.12 on MacOS 10.11.6:

``` python
import sophy

# assumes that /tmp/foo does not exist before the script is run
env = sophy.Sophia('/tmp/foo', [('foo', 'string')])
db = env['foo']
db['a'] = 'xxx'
db['b'] = 'yyy'
db['c'] = 'zzz'
env.close()

env = sophy.Sophia('/tmp/foo', [('foo', 'string')])
db = env['foo']
for (k, v) in db:
    print k, v
env.close()
```

**Comment by coleifer** [comment]
It's worth noting that if, in the second example, you use different names for `env` and `db` (`env2` and `db2`), the segfault doesn't happen. Something to do with the destructor I'm sure, just not quite clear on what's going on here.

**Comment by coleifer** [comment]
Working on a rewrite which will fix this and also support the latest version 2.2. It's in a branch and I anticipate merging in the next day or so.

**Comment by coleifer** [comment]
This is fixed in master. The latest changes are also deployed to PyPI as version 0.2.0.

To fully support Sophia's multi-field key and value schema, Sophy has a new API for instantiating environments. Here is the equivalent code in Sophy 0.2.0:

```python
from sophy import *
env = Sophia('/tmp/sophy-gh-10')
schema = Schema(key_parts=[StringIndex('key')], value_parts=[StringIndex('val')])
db = env.add_database('foo', schema)

env.open()  # True
db['a'] = 'xxx'
db['b'] = 'yyy'
db['c'] = 'zzz'
env.close()  # True

env.open()  # True
for key, value in db:
    print key, value
# a xxx
# b yyy
# c zzz
env.close()

env = Sophia('/tmp/sophia-gh-10')
db = env.add_database('foo', schema)
env.open()  # True

for key, value in db:
    print key, value
# a xxx
# b yyy
# c zzz

env.close()  # True
```

**Comment by lebedov** [comment]
Thanks!
