### ISSUE TITLE
Can't create new environment

### ISSUE THREAD

**Issue by khaledkbadr** [coleifer/sophy#11]
When I run the following code:
```python
import sophy
# assumes that /tmp/foo does not exist before the script is run
env = Sophia('/tmp/foo')
db = env.create_database('mydb', 'string')
```

 I get the following error:
```
Exception ignored in: 'sophy.Sophia.open'
Traceback (most recent call last):
  File "sophy.pyx", line 154, in sophy._ConfigManager.apply_all (sophy.c:6382)
  File "sophy.pyx", line 150, in sophy._ConfigManager.apply_config (sophy.c:6215)
  File "sophy.pyx", line 73, in sophy._check (sophy.c:3704)
Exception: sophia/runtime/sr_conf.c:339 bad configuration path: db.b'foo'.mmap
```

Is there any configuration I should do?

**Comment by coleifer** [comment]
What version are you using?

**Comment by khaledkbadr** [comment]
0.1.6 on Ubuntu & MacOS

**Comment by coleifer** [comment]
Looks like a Python3 issue.

**Comment by esennesh** [comment]
Ok, but you said in the README sophy works with Python3.  So how do we work around the issue?

**Comment by coleifer** [comment]
Working on a rewrite which will work with py3 and also support the latest version 2.2. It's in a branch and I anticipate merging in the next day or so.

**Comment by coleifer** [comment]
Python3 support, as well as support for Sophia v2.2, has been merged into master and deployed on PyPI as `sophy v0.2.0`.

The APIs used for creating an environment / setting up a database have changed, so please refer to either the [README](https://github.com/coleifer/sophy/blob/master/README.md) or the [test cases](https://github.com/coleifer/sophy/blob/master/tests.py).
