### ISSUE TITLE
Querying a part of index and value?

### ISSUE THREAD

**Issue by catroot** [coleifer/sophy#14]
I wonder if there is possibility to query a part of complex indexes or even query for value?
Suppose we have a schema:
```python
schema = Schema(key_parts=[StringIndex('key'), StringIndex('predicate')],
value_parts=[StringIndex('value')])
```
Since we have defined StringIndex for value and for key and predicate, can i query for a part of index or for specific value?

**Comment by coleifer** [comment]
I don't think that's how it's designed to work...
