### ISSUE TITLE
Closing database safely

### ISSUE THREAD

**Issue by gdmka** [coleifer/sophy#5]
Not sure if there is a special method in the API (i didn't find one) but i do have some issues (_segfaults_ to be accurate) when i try to close sophia instance through **close** method defined here https://github.com/coleifer/sophy/blob/master/sophy.pyx#L545

This issue came out of a problem with Flask's code reloader which opened too many files resulting in
`Exception Exception: Exception("sophia/log/sl.c:61 log file '' open error: Too many open files",) in 'sophy.Sophia.open' ignored`

**Comment by coleifer** [comment]
Hmm... can you provide steps to reproduce?

**Comment by gdmka** [comment]
Sorry for a huge delay. 
As for now i cannot reproduce it. It seems that the problem was in a wrapper that i implemented around the Sophia instance (it could have been instantiating too many  opens in init w/o proper close).
