### ISSUE TITLE
Encoding problems?

### ISSUE THREAD

**Issue by jnurmine** [coleifer/sophy#6]
Hi,

I used virtualenv to set up a Python 3.4.3; then did "pip install cython", cloned master branch of sophy (commit 2cac2f5 as HEAD), followed by successful "python setup.py build" and "python setup.py install".

When running "python tests.py", all tests fail due to:
`Exception: sophia/runtime/sr_conf.c:339 bad configuration path: db.b'db-test'.mmap`

Full output (all test cases fail in the same way):

```
ERROR: test_version (main.TestConfiguration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 20, in setUp
    self.sophia = self.create_env()
  File "tests.py", line 29, in create_env
    return Sophia(TEST_DIR, [(DB_NAME, self._index_type)])
  File "sophy.pyx", line 208, in sophy.Sophia.init (sophy.c:6464)
    self.open()
  File "sophy.pyx", line 226, in sophy.Sophia.open (sophy.c:6733)
    self.config.apply_all()
  File "sophy.pyx", line 159, in sophy._ConfigManager.apply_all (sophy.c:5877)
    self.apply_config(key, value)
  File "sophy.pyx", line 155, in sophy._ConfigManager.apply_config (sophy.c:5707)
    _check(self.sophia.handle, rc)
  File "sophy.pyx", line 78, in sophy._check (sophy.c:3297)
    raise Exception(error)
Exception: sophia/runtime/sr_conf.c:339 bad configuration path: db.b'db-test'.mmap
```

Same `b'db-test'` appears when building from the tag 0.1.6.

Not sure what causes this. Looks like something with encoding/decoding... maybe whatever is encoded must be decoded when used later for string concatenation (and subsequent re-encode).

I also wonder if this is somehow an issue with locales. Mine are set to sv_SE.UTF-8.

**Comment by alekibango** [comment]
it is python3 compatibility issue. With python2 it worked to me. But python2 is really becoming obsolete.

**Comment by coleifer** [comment]
Working on a rewrite which will work with py3 and also support the latest version 2.2. It's in a branch and I anticipate merging in the next day or so.

**Comment by coleifer** [comment]
Python 3 support merged into master and deployed to PyPI as `sophy 0.2.0`.
