### ISSUE TITLE
How to limit the memory used by sophia

### ISSUE THREAD

**Issue by amirouche** [coleifer/sophy#8]
Héllo,

I'd like to use sophia for my [sotoki](https://github.com/kiwix/sotoki) project to replace sqlite, pgsql or wiredtiger.

Here is my code:

``` python
            from sophy import Sophia
            from msgpack import loads, dumps

            env = Sophia(db, auto_open=False)
            env.memory_limit = 1024 * 1024 * 1024
            env.open()

            posts = env.create_database('Post', 'u32')


            filepath = os.path.join(dump, klass.filename())
            for data in iterate('dump'):
                 posts[int(data['Id'])] = dumps(data)
            for key, data in posts.cursor():
                uid = key
                values = loads(data)
            env.close()
```

But sophia seem to use all the memory available even if I've set a memory limit. What I am doing wrong?

**Comment by coleifer** [comment]
I'd suggest reading the docs here:

http://sophia.systems/v2.1/conf/memory.html

Problem is very likely a result of misunderstanding the settings or a bug in sophia itself, as this project provides only a thin wrapper around the C code.
